// This file is auto-generated by openapi-typescript when the backend team provides an OpenAPI spec.
// Run: npx openapi-typescript <openapi-spec-url> -o src/types/api.generated.ts
// Do not edit manually.

export {};
